### ISSUE TITLE
Can unintentionally select multiple chapters

### ISSUE THREAD

**Issue by CornHusker89** [smallketchup82/rezero-summarizer#2] opened 2023-10-26 00:32 UTC
You can unintentionally select multiple chapters when inputting a single digit chapter

**Comment by smallketchup82** [comment] 2023-10-31 13:38
From what I know, this is fixed. But I'll keep the issue open until we can confirm it is gone

**Comment by smallketchup82** [comment] 2023-11-03 02:39
So this part seems to be whats causing the issue. But it shouldn't be doing that. The space at the end of the file ensures that it matches the chapter and a space

https://github.com/smallketchup82/rezero-summarizer/blob/24a8d484409439afd4e823599ee08ca320468a23/main.py#L145-L154

Also quick explanation of the issue
![image](https://github.com/smallketchup82/rezero-summarizer/assets/69545310/9b49774e-f29c-4a97-b773-0fb2dfd7e8be)
The only thing is that, this is already done. There is already a space at the end. I haven't experienced this issue myself yet.

I'll probably close the issue as not planned for now, until it can be reproduced (someone gets the bug again)

**Closed by smallketchup82** 2023-11-03 02:39 UTC
